###
get http://localhost:3000/posts

### 
post http://localhost:3000/posts
Content-Type: application/json

{
    "id" : "1",
    "title" : "first post"
}

###
delete http://localhost:3000/posts
Content-Type: application/json

{
    "id" : "1",
    "title" : "first post"
}